# 服务器配置
# 全局免费模式，若为true则所有传送免费（无视经济插件）
free-mode: false

# 当前服务器名称（用于检测是否在同一服务器）
current-server: "服务器名称"

# 目标服务器名称
servers:
  kongdao:
    cost: 1  # 修改此值即可调整扣款金额
  zhucheng:
    cost: 1 # 以此类推即可

